name: CI
on:
  pull_request:
  push:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: coursier/cache-action@v6
      - name: Compile
        run: sbt test:compile
      - name: Archive compile results
        uses: actions/upload-artifact@v3
        with:
          name: compile-result
          path: target
          retention-days: 5
  test:
    needs: compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tests: [A-I, J-N, O, Q-Z]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Download a compile classes
        uses: actions/download-artifact@v3
        with:
          name: compile-result
      - name: Test .*\\.[${{ matrix.tests }}].*
        run: sbt "testOnly .*\\.[${{ matrix.tests }}].*"
  test-all:
    needs: compile, test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Download a compile classes
        uses: actions/download-artifact@v3
        with:
          name: compile-result
      - name: Test .*\\.[${{ matrix.tests }}].*
        run: sbt test
